const express = require('express')
require('dotenv').config()
const app = express()
const cors = require('cors')
app.use(cors())
const carRoutes = require('./api/carsRoutes')
const userRoutes = require('./api/userRoutes')
const authRoutes = require('./api/authRoutes')
const brandRoutes = require('./api/brandRoutes')
const categoryRoutes = require('./api/categoryRoutes')
const subcategoryRoutes = require('./api/subcategoryRoutes')
const itemRoutes = require('./api/itemRoutes')
const cartRoutes = require('./api/cartRoutes')
const wishlistRoutes = require('./api/wishlistRoutes')
const orderRoutes = require('./api/orderRoutes')
const orderDetailsRoutes = require('./api/orderDetailsRoutes')
const connect = require('./config/connectDB')

console.log(connect())

//Make folder public
const { static } = require('express')

app.use('/uploads',express.static('uploads'))
app.use('/api/car',carRoutes)
app.use('/api/user',userRoutes)
app.use('/api/auth',authRoutes)
app.use('/api/brand',brandRoutes)
app.use('/api/category',categoryRoutes)
app.use('/api/subcategory',subcategoryRoutes)
app.use('/api/item',itemRoutes)
app.use('/api/cart',cartRoutes)
app.use('/api/wishlist',wishlistRoutes)
app.use('/api/order',orderRoutes)
app.use('/api/orderdetails',orderDetailsRoutes)
//Use environment's port
app.listen(process.env.PORT||5000,()=>{
    console.log("server started")
})